# Generated by Django 5.2.8 on 2025-12-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_toolkit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentoperation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("merge", "Merge"),
                    ("split", "Split"),
                    ("extract", "Extract"),
                ],
                max_length=10,
            ),
        ),
    ]
