# Generated by Django 5.2.8 on 2025-12-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_toolkit", "0002_alter_documentoperation_operation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentartifact",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="artifacts/%Y/%m/%d/"
            ),
        ),
    ]
